version: "2"
run:
  go: "1.22"
linters:
  enable:
    - bodyclose
    - contextcheck
    - exhaustive
    - forcetypeassert
    - misspell
    - nilerr
    - noctx
    - wrapcheck
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    wrapcheck:
      ignore-sigs:
        - fmt.Errorf(
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - wrapcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/Mozes721/portfolio-pulse
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
